### ISSUE TITLE
AnalysisPrograms container for HPC

### ISSUE THREAD

**Issue by ThomasLuypaertGitHub** [QutEcoacoustics/audio-analysis#309] opened 2020-03-25 17:17 UTC
## Is your feature request related to a problem? Please describe.
At present I'm running my computations on a desktop computer, however this limits what is possible on my data due to time constraints.  I would like to run AnalysisPrograms on a HPC platform, and was wondering whether there is an existing container to do so? Or perhaps instructions on building one?

## Describe the solution you'd like

A container for AnalysisPrograms. In previous email communications, a Singularity container with a Debian image was suggested. 

## Describe alternatives you've considered

/

## Additional context

/

**Comment by atruskie** [comment] 2020-03-28 05:37
Closing as duplicate of #195

@ThomasLuypaertGitHub - we're currently going through a massive rewrite to make AP.exe much easier to use on HPCs and OSX and Linux. You can track progress in the https://github.com/QutEcoacoustics/audio-analysis/tree/azure-pipelines branch.

**Closed by atruskie** 2020-03-28 05:37 UTC
