### ISSUE TITLE
Fix display of Debug spectrograms and write unit tests

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#300] opened 2020-03-03 23:28 UTC
## Describe the bug
The drawing of debug spectrograms, in particular the display of score tracks and the overlay of matrix scores, is yet to be properly checked. Need to write unit tests for these.

The overlay of score matrices on standard scale spectrograms has not been checked for some time.
This work needs to be done in order to facilitate the writing of new generic recognizers as in Issue #297.

**Comment by atruskie** [comment] 2020-03-03 23:48
Can you show the visual errors here, please?

**Comment by atruskie** [comment] 2020-03-20 01:38
Ok, some of this work has been done in #301.

More remains.

# Text Anti-Aliasing

Compare old image vs new:

# old
![image](https://user-images.githubusercontent.com/1452968/77127560-c3286880-6a98-11ea-91fa-ee04a0c974d3.png)

![image](https://user-images.githubusercontent.com/1452968/77129243-fa9a1380-6a9e-11ea-9a0d-aa0e8a506711.png)

# new

![image](https://user-images.githubusercontent.com/1452968/77127651-08e53100-6a99-11ea-9130-9c4c5d8256e3.png)

![image](https://user-images.githubusercontent.com/1452968/77129189-c32b6700-6a9e-11ea-8085-fcda76aef64f.png)

# issues

- the anti-aliasing on the text is the new one is way too aggressive
- the quality of ImageSharp anti-aliasing seems sub-par
    - https://github.com/SixLabors/ImageSharp/issues/138 (ensure we're not using a pen)?
    - ensure sub-pixel alignment is occurring
    - It looks like we won't have access to clear type font rendering
- the font seems to generally be smaller (DPI issue?).
    - Dimensions of the zero in Y scale is 6x9 in old, and 4x7 in new)
    - Dimensions of the `W` in _Whistle_ are 7x6 in old and 5x5 in new 
    - Title `E` in title bar seems to be 8*9 in old and 5x7 in new
- rectangle axes segments need to be updated to be non-AA
- horizontal divider needs to be updated to be non-AA
- the rectangle is missing a pixel in lower right corner

@towsey - can you please precisely identify and changes you've made to the fonts/sizes of the text in question between the conversion and this point - I don't want to attribute behaviour to changes that are yours and not a bug.


@towsey - you should continue your work on the recognisers despite this image imperfections. We'll fix them up as we go and images will progressively get better.

**Comment by atruskie** [comment] 2020-03-20 04:50
Note: an asset committed in 04f9b044e4c0e281a6a681580bdd46c223be7037 (https://github.com/QutEcoacoustics/audio-analysis/blob/04f9b044e4c0e281a6a681580bdd46c223be7037/tests/Fixtures/EventTests_SuperimposeEventsOnImage.png) is actually reflective of the bug described in this issue and will need to be adjusted when this is fixed.

**Comment by atruskie** [comment] 2021-02-16 00:39
I think most of the issues highlighted here have been dealt with - except for the antialiasing.

Opening that in a new issue for easier tracking. See #449

**Closed by atruskie** 2021-02-16 00:39 UTC
